FROM python:3.10-alpine

ENV DJANGO_SETTINGS_MODULE=settings.settings_prod

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY server/ ./

CMD ./manage.py migrate \
    && gunicorn settings.wsgi -b 0.0.0.0:8000