version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    env_file: .env
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    restart: unless-stopped
