version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - "./server/:/app/server/"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"