version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    restart: unless-stopped
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
