# Generated by Django 4.0.4 on 2023-01-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_image_nsfw"),
    ]

    operations = [
        migrations.AddField(
            model_name="twitteruser",
            name="num_hits",
            field=models.IntegerField(
                default=0, help_text="Number of times this user has been searched for."
            ),
        ),
        migrations.AddField(
            model_name="twitteruser",
            name="num_scrapes",
            field=models.IntegerField(
                default=1,
                help_text="Number of times this user's images have been scraped.",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="key",
            field=models.CharField(
                help_text="The media key of the image (twitter ID).",
                max_length=50,
                unique=True,
            ),
        ),
    ]
